### ISSUE TITLE
[Bug] bitnami-shell appears to have been removed from docker.io

### ISSUE THREAD

**Issue by j99ca** [open-edge-platform/geti_v2#486]
### 🧩 Issue type

Bug 🐞

### 📄 Description

In the yaml file:
``platform/services/credit/chart/values.yaml``

It has the lines:

```
  debian:
    registry: docker.io
    repository: bitnami
    name: bitnami-shell:11-debian-11-r136
```

But that [no longer appears to exist](https://hub.docker.com/r/bitnami/bitnami-shell)?

I think this (and possibly other references) might need to be replaced with ``bitnami/os-shell``?

### 📦 Geti version

2.10.1

### 🖥️ Operating System

Ubuntu 22.04
